export enum CallStatusENUM {
    PENDING = "PENDING",
    QUEUED = "QUEUED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    MISSED = "MISSED",
    NOT_COMPLETED = "NOT_COMPLETED",
    CANCELED = "CANCELED"
}